name: calibration_routine
description: A package for calibrating a set of positioners to find an ion.
version: 0.1.0+1
publish_to: none

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  curve_fitting:
    path: ../curve_fitting
  dartz: ^0.10.1
  equatable: ^2.0.3
  equations: ^4.1.0
  freezed_annotation: ^2.1.0
  ion_response:
    path: ../ion_response
  positioner:
    path: ../positioner

dev_dependencies:
  build_runner: ^2.2.1
  freezed: ^2.0.4
  gaussian:
    path: ../gaussian
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.1.0
