name: curve_fitting
description: A package for creating a gaussian distribution
version: 0.1.0+1
publish_to: none

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  equatable: ^2.0.3
  equations: ^4.1.0

dev_dependencies:
  gaussian:
    path: ../gaussian
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.1.0
