name: ion_response
description: A package for reading the response from the ions
version: 0.1.0+1
publish_to: none

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  dartz: ^0.10.1
  freezed_annotation: ^2.1.0
  gaussian:
    path: ../gaussian
  meta: ^1.8.0
  positioner:
    path: ../positioner

dev_dependencies:
  build_runner: ^2.2.1
  freezed: ^2.0.4
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.1.0
